###########################################################################
# This file is managed by Chef.
# DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN!
###########################################################################
export HADOOP_PREFIX=/opt/myapp/hadoop
