---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "saturday"
      time: "07:00"
      timezone: "Asia/Tokyo"
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "saturday"
      time: "07:00"
      timezone: "Asia/Tokyo"
