[tool.poetry]
name = "yuokada-github-com"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "yuokada"}]

[tool.poetry.dependencies]
python = "^3.9"
certifi = "^2023.5.7"
sphinx = "5.1.1"
sphinx-bootstrap-theme = "^0.8.1"
sphinxtogithub = {git = "https://github.com/proycon/sphinx-to-github.git", rev = "9b61be70ccfbec99724544c3e94ed1c43fb5295c"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
