# This file is managed by Chef.
# DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN!
###########################################################################
export HIVE_HOME=/opt/qe/hive
export HCATALOG_HOME=${HIVE_HOME}/hcatalog
export TEMPLETON_HOME=${HIVE_HOME}/hcatalog
export HIVE_AUX_JARS_PATH=${HADOOP_PREFIX}/share/hadoop/tools/lib
