name: Build Sphinx Docs

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip uv
          uv export --all-groups --no-hashes |grep -v "urllib\|pyyaml" | sudo pip install -r /dev/stdin
      - name: Build HTML
        run: make html
      - name: Commit built docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          cd build/html
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git checkout gh-pages
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Update docs"
            git push origin gh-pages
          fi
          cd ../..
          git add build/html
          if ! git diff --cached --quiet; then
            git commit -m "Update submodule"
            git push origin master
          fi
